/** Declaration file generated by dts-gen */

export = blueimp_md5;

declare function blueimp_md5(string: any, key?: any, raw?: any): any;

declare namespace blueimp_md5 {
    const prototype: {
    };

}

